"""Generate the immutable MQL5 table from the source-only DESIGN ledger."""

from __future__ import annotations

import hashlib
import importlib.util
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
SOURCE = (
    ROOT / "02. AlphaFactory/data/databento/cme_6e_event_depth_transfer/"
    "HYP-EVENT-DEPTH-TRANSFER-EURUSD-TICK-005/"
    "EVENTDEPTHTRANSFER005-MBP10-CONTINUATION-001/"
    "combined_source_classification_ledger.jsonl"
)
OUTPUT = ROOT / "03. EA Developer/EA_EventDepthTransfer/resources/event_depth_transfer_006_table.mqh"
CLOCK_MODULE = ROOT / "02. AlphaFactory/tools/research/fivepercent_server_clock.py"
EXPECTED_SOURCE_SHA256 = "4DE647CB8CC39F5CD26D10D844C11F1B5A493DAF7C69F2CB633AB361912326F0"


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def load_clock_module():
    spec = importlib.util.spec_from_file_location("fivepercent_server_clock", CLOCK_MODULE)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load canonical FivePercent clock module")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def parse_utc(value: str) -> datetime:
    parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        raise ValueError("event timestamp lacks UTC offset")
    return parsed.astimezone(timezone.utc)


def utc_to_server(utc: datetime, clock) -> tuple[datetime, int]:
    candidates: list[tuple[datetime, int]] = []
    for offset in (2, 3):
        server = (utc + timedelta(hours=offset)).replace(tzinfo=None)
        if clock.server_to_utc(server).replace(tzinfo=timezone.utc) == utc:
            candidates.append((server, offset))
    if len(candidates) != 1:
        raise ValueError(f"ambiguous FivePercent UTC->server mapping: {utc.isoformat()}")
    return candidates[0]


def to_epoch_msc_naive(value: datetime) -> int:
    return int(value.replace(tzinfo=timezone.utc).timestamp() * 1000)


def load_rows() -> list[dict[str, int | str]]:
    if sha256_file(SOURCE) != EXPECTED_SOURCE_SHA256:
        raise ValueError("combined source ledger SHA256 mismatch")
    clock = load_clock_module()
    rows: list[dict[str, int | str]] = []
    for line in SOURCE.read_text(encoding="ascii").splitlines():
        raw = json.loads(line)
        utc = parse_utc(str(raw["event_time_utc"]))
        server, offset = utc_to_server(utc, clock)
        rows.append({
            "event_id": str(raw["event_clock_id"]),
            "utc_msc": int(utc.timestamp() * 1000),
            "server_msc": to_epoch_msc_naive(server),
            "offset_h": offset,
            "direction": int(raw.get("effective_direction") or 0),
            "status": str(raw["status"]),
        })
    if len(rows) != 329 or len({row["event_id"] for row in rows}) != 329:
        raise ValueError("expected exactly 329 unique DESIGN identities")
    if [row["event_id"] for row in rows] != [f"EVT{i:04d}" for i in range(1, 330)]:
        raise ValueError("event identity sequence mismatch")
    if any(int(rows[i]["server_msc"]) >= int(rows[i + 1]["server_msc"]) for i in range(328)):
        raise ValueError("server clocks are not strictly increasing")
    directions = [int(row["direction"]) for row in rows]
    if (directions.count(1), directions.count(-1), directions.count(0)) != (162, 156, 11):
        raise ValueError("frozen direction counts changed")
    return rows


def canonical_table(rows: list[dict[str, int | str]]) -> bytes:
    return "".join(
        f"{row['event_id']},{row['utc_msc']},{row['server_msc']},{row['direction']}\n"
        for row in rows
    ).encode("utf-8")


def mql_array(name: str, kind: str, values: list[str]) -> str:
    return f"const {kind} {name}[AF_DEPTH_EVENT_COUNT]={{\n   " + ",\n   ".join(values) + "\n};\n"


def render(rows: list[dict[str, int | str]]) -> str:
    table_sha = hashlib.sha256(canonical_table(rows)).hexdigest().upper()
    return "".join([
        "// Generated by research/generate_event_depth_transfer_006_table.py; do not hand-edit.\n",
        "#ifndef EVENT_DEPTH_TRANSFER_006_TABLE_MQH\n#define EVENT_DEPTH_TRANSFER_006_TABLE_MQH\n\n",
        "#define AF_DEPTH_EVENT_COUNT 329\n",
        f'const string AF_DEPTH_SOURCE_SHA256="{EXPECTED_SOURCE_SHA256}";\n',
        f'const string AF_DEPTH_TABLE_SHA256="{table_sha}";\n\n',
        mql_array("AF_DEPTH_EVENT_ID", "string", [f'"{row["event_id"]}"' for row in rows]),
        "\n", mql_array("AF_DEPTH_UTC_MSC", "long", [str(row["utc_msc"]) for row in rows]),
        "\n", mql_array("AF_DEPTH_SERVER_MSC", "long", [str(row["server_msc"]) for row in rows]),
        "\n", mql_array("AF_DEPTH_DIRECTION", "int", [str(row["direction"]) for row in rows]),
        "\n#endif\n",
    ])


def main() -> None:
    rows = load_rows()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(rows), encoding="utf-8", newline="\n")
    print(
        "EVENTDEPTHTRANSFER006_TABLE_OK "
        f"events={len(rows)} source_sha256={EXPECTED_SOURCE_SHA256} "
        f"table_sha256={hashlib.sha256(canonical_table(rows)).hexdigest().upper()}"
    )


if __name__ == "__main__":
    main()

