#!/usr/bin/env python3
"""Append registry rows for EQHL follow-on Wave4 probes + intake extras."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(r"d:\Trading EA MT5")
REG = ROOT / "03. EA Developer" / "EA_SonicR" / "research" / "CANDIDATE_REGISTRY.jsonl"

rows = [
    {
        "record_type": "candidate",
        "schema_version": 1,
        "hypothesis_id": "HYP-H1-RV-COMPRESS-BREAK-001",
        "state": "killed",
        "parent_candidate": None,
        "feature_family": "h1_rv_compress_donchian_break",
        "lane": "discovery_wave4_20260714",
        "setup_type": "H1 range-RV compress → Donchian break; RR=2.5",
        "symbol": "USDJPY",
        "timeframe": "H1",
        "window": "2021.01.01-2025.12.31",
        "model": 0,
        "source_provenance": "Offline probe kill-fast; Model0 withheld",
        "prereg_path": "03. EA Developer/EA_SonicR/research/preregs/20260714_H_H1_RV_COMPRESS_BREAK_001_PREREG.md",
        "readout_path": "03. EA Developer/EA_SonicR/research/readouts/20260714_HYP_H1_RV_COMPRESS_BREAK_001_READOUT.md",
        "source_path": "03. EA Developer/EA_H1RVCompressBreak/EA_H1RVCompressBreak.mq5",
        "run_ids": [],
        "metrics": {
            "trades": 94,
            "pf": 1.421,
            "tpw": 0.361,
            "exp": 106.99,
            "pf_cost_x1_5": 1.337,
            "pf_cost_x2": 1.310,
        },
        "validation": {
            "offline_probe": "preflight/20260714_H1_RV_COMPRESS_BREAK_OFFLINE_PROBE.json",
            "status": "KILLED_AT_OFFLINE_PROBE",
            "model0": "NOT_RUN_FAIL_CLOSED",
        },
        "cost_grade": "UNVERIFIED_SYNTHETIC_PLUS_REPORT_ONLY_12",
        "verdict": "KILLED_AT_OFFLINE_PROBE",
        "reason": "tpw 0.36 sparse; thick PF/cost diagnostic only — not GOAL book",
        "updated_at": "2026-07-14",
    },
    {
        "record_type": "candidate",
        "schema_version": 1,
        "hypothesis_id": "HYP-M15-IB-OVERLAP-BREAK-001",
        "state": "preregistered",
        "parent_candidate": None,
        "feature_family": "m15_london_ib_overlap_break",
        "lane": "discovery_wave4_20260714",
        "setup_type": "London IB lock → L/NY overlap M15 break; RR=2.5",
        "symbol": "USDJPY",
        "timeframe": "M15",
        "window": "2021.01.01-2025.12.31",
        "model": 0,
        "source_provenance": "Offline probe survive; Model0 blocked by Real terminal64",
        "prereg_path": "03. EA Developer/EA_SonicR/research/preregs/20260714_H_M15_IB_OVERLAP_BREAK_001_PREREG.md",
        "readout_path": "03. EA Developer/EA_SonicR/research/readouts/20260714_HYP_M15_IB_OVERLAP_BREAK_001_READOUT.md",
        "source_path": "03. EA Developer/EA_M15IBOverlapBreak/EA_M15IBOverlapBreak.mq5",
        "run_ids": [],
        "metrics": {
            "trades": 990,
            "pf": 1.203,
            "tpw": 3.797,
            "exp": 41.96,
            "pf_cost_x1": 1.141,
            "pf_cost_x1_5": 1.111,
            "pf_cost_x2": 1.082,
        },
        "validation": {
            "offline_probe": "preflight/20260714_M15_IB_OVERLAP_BREAK_OFFLINE_PROBE.json",
            "status": "PROBE_SURVIVE_MODEL0_BLOCKED_REAL_TERMINAL",
            "blocker_pid": 27628,
            "blocker_server": "FivePercentOnline-Real",
        },
        "cost_grade": "UNVERIFIED_SYNTHETIC_PLUS_REPORT_ONLY_12",
        "verdict": "PROBE_SURVIVE__MODEL0_QUEUED",
        "reason": "Survives hard kill; optimistic PF<1.30 and x1.5 FAIL research screen; Model0 still required under tester current when MT exclusive",
        "updated_at": "2026-07-14",
    },
    {
        "record_type": "candidate",
        "schema_version": 1,
        "hypothesis_id": "HYP-GBPJPY-LEAD-USDJPY-H1-001",
        "state": "preregistered",
        "parent_candidate": None,
        "feature_family": "h1_gbpjpy_atr_impulse_lead_usdjpy",
        "lane": "discovery_wave4_20260714",
        "setup_type": "GBPJPY H1 ATR impulse → USDJPY legal lag; RR=2.5",
        "symbol": "USDJPY",
        "timeframe": "H1",
        "window": "2021.01.01-2025.12.31",
        "model": 0,
        "source_provenance": "Offline probe survive; Model0 blocked by Real terminal64",
        "prereg_path": "03. EA Developer/EA_SonicR/research/preregs/20260714_H_GBPJPY_LEAD_USDJPY_H1_001_PREREG.md",
        "readout_path": "03. EA Developer/EA_SonicR/research/readouts/20260714_HYP_GBPJPY_LEAD_USDJPY_H1_001_READOUT.md",
        "source_path": "03. EA Developer/EA_H1GBPJPYLead/EA_H1GBPJPYLead.mq5",
        "run_ids": [],
        "metrics": {
            "trades": 1284,
            "pf": 1.147,
            "tpw": 4.925,
            "exp": 32.28,
            "pf_cost_x1": 1.090,
            "pf_cost_x1_5": 1.062,
            "pf_cost_x2": 1.036,
        },
        "validation": {
            "offline_probe": "preflight/20260714_GBPJPY_LEAD_USDJPY_H1_OFFLINE_PROBE.json",
            "status": "PROBE_SURVIVE_MODEL0_BLOCKED_REAL_TERMINAL",
            "blocker_pid": 27628,
        },
        "cost_grade": "UNVERIFIED_SYNTHETIC_PLUS_REPORT_ONLY_12",
        "verdict": "PROBE_SURVIVE__MODEL0_QUEUED",
        "reason": "Survives hard kill; optimistic PF/cost below research HIT; Model0 queued",
        "updated_at": "2026-07-14",
    },
    {
        "record_type": "candidate",
        "schema_version": 1,
        "hypothesis_id": "HYP-H1-EMA-STACK-PB-001",
        "state": "killed",
        "parent_candidate": "post_eqhl_independent_probe",
        "feature_family": "h1_ema_stack_pullback",
        "lane": "post_eqhl_intake_kill_20260714",
        "setup_type": "H1 EMA8/21/50 stack PB to EMA21 resume; RR=2.5",
        "symbol": "USDJPY",
        "timeframe": "H1",
        "window": "2021.01.01-2025.12.31",
        "model": "offline_probe_only",
        "source_provenance": "Invented after EQHL intake-kill; not ITSM densify",
        "prereg_path": None,
        "readout_path": "03. EA Developer/EA_SonicR/research/readouts/20260714_EQHL_WAVE4_CLOSEOUT.md",
        "source_path": None,
        "run_ids": [],
        "metrics": {"trades": 1634, "pf": 1.022, "tpw": 6.267},
        "validation": {
            "offline_probe": "preflight/20260714_H1_EMA_STACK_PB_OFFLINE_PROBE.json",
            "status": "KILLED_AT_OFFLINE_PROBE",
        },
        "verdict": "KILLED_AT_OFFLINE_PROBE",
        "reason": "tpw 6.27>6 and PF~1.02 thin; Model0 withheld",
        "updated_at": "2026-07-14",
    },
    {
        "record_type": "candidate",
        "schema_version": 1,
        "hypothesis_id": "HYP-H1-LONDON-OPEN-DRIVE-001",
        "state": "killed",
        "parent_candidate": "post_eqhl_independent_probe",
        "feature_family": "h1_london_open_drive_continuation",
        "lane": "post_eqhl_intake_kill_20260714",
        "setup_type": "London H1 hour7 drive body+close-third continuation; RR=2.5",
        "symbol": "USDJPY",
        "timeframe": "H1",
        "window": "2021.01.01-2025.12.31",
        "model": "offline_probe_only",
        "source_provenance": "Independent of LondonORB M15 box; thick-sparse kill",
        "prereg_path": None,
        "readout_path": "03. EA Developer/EA_SonicR/research/readouts/20260714_EQHL_WAVE4_CLOSEOUT.md",
        "source_path": None,
        "run_ids": [],
        "metrics": {
            "trades": 104,
            "pf": 1.349,
            "tpw": 0.399,
            "pf_cost_x1_5": 1.267,
            "pf_cost_x2": 1.241,
        },
        "validation": {
            "offline_probe": "preflight/20260714_H1_LONDON_OPEN_DRIVE_OFFLINE_PROBE.json",
            "status": "KILLED_AT_OFFLINE_PROBE",
        },
        "verdict": "KILLED_AT_OFFLINE_PROBE",
        "reason": "tpw 0.40 sparse (thick diagnostic like LondonNY/RV); not GOAL book",
        "updated_at": "2026-07-14",
    },
    {
        "record_type": "candidate",
        "schema_version": 1,
        "hypothesis_id": "HYP-H1-ATR-PCTILE-BREAK-001",
        "state": "idea",
        "parent_candidate": None,
        "feature_family": "h1_atr_percentile_donchian_break",
        "lane": "post_eqhl_next_stub_20260714",
        "setup_type": "H1 Donchian break only when ATR%ile in [40,70]; RR=2.5 a priori",
        "symbol": "USDJPY",
        "timeframe": "H1",
        "window": "2021.01.01-2025.12.31",
        "model": "stub_only",
        "source_provenance": "Next stub after EQHL kill + Wave4 probes; not ATR-regime-mom densify; not LowVol fade",
        "prereg_path": None,
        "readout_path": "03. EA Developer/EA_SonicR/research/readouts/20260714_H1_ATR_PCTILE_BREAK_STUB.md",
        "source_path": None,
        "run_ids": [],
        "metrics": None,
        "validation": {"status": "STUB_PREPARED_NEEDS_DEDUP_FREEZE"},
        "verdict": "STUB_NEXT",
        "reason": "Prepared successor; freeze de-dup+prereg before code",
        "updated_at": "2026-07-14",
    },
]


def main() -> None:
    with REG.open("a", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
            print(r["hypothesis_id"], r["verdict"])


if __name__ == "__main__":
    main()
