"""clock_vectors.py - golden vectors for the MQL5 PA_Clock/PA_Session port.

Generates tests/clock_vectors.inc (MQL5 array literals) + a readable CSV.
Truth = lib/pa_clock.py + lib/pa_fill.py entry-veto logic, run inline (light
job, no pa_slots needed - pure arithmetic on ~200 epochs).

Coverage (the mandated weeks + every known bug shape):
- winter week  : 2019-01-07 .. 2019-01-13 (EU server offset +2)
- summer week  : 2019-07-01 .. 2019-07-07 (offset +3)
- DST week     : 2019-03-25 .. 2019-03-31 (last Sunday of March +1h flip)
- DST week     : 2019-10-25 .. 2019-10-31 (last Sunday of October +1h flip)
- regression   : server hours 00:00-03:59 (negative utc_min bug), Friday
                 19:55/20:00 boundary, Sat/Sun weekend veto, Monday rollover.

Per vector row: server epoch -> offset_h, utc_min (close), srv_min (close),
dow (close, Monday=0), entry_veto (0 none /1 friday /2 weekend), in_session
(eu|us union on the close utc_min).
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LIB = os.path.join(os.path.dirname(os.path.dirname(HERE)), "lib")
sys.path.insert(0, LIB)
import pa_clock  # noqa: E402

DAY = 86400


def _srv(y, m, d, hh=0, mm=0):
    """Server epoch for a wall-clock date: epoch of that civil date is what
    we need - the server clock IS the epoch axis (offset applied on read)."""
    import calendar
    return calendar.timegm((y, m, d, hh, mm, 0))


def veto(t):
    """pa_fill.py:196-215 corrected-mode entry veto on the bar OPEN epoch."""
    srv_h = (t % DAY) // 3600
    dow = pa_clock.server_dow(t)
    if dow >= 5:
        return 2                      # VETO_WEEKEND
    if dow == 4 and srv_h >= 20:
        return 1                      # VETO_FRIDAY
    return 0


def in_session(utc_min):
    return int((300 <= utc_min < 660) or (690 <= utc_min < 1050))


def gen():
    pts = []
    # ---- dense boundary sweeps per test week ------------------------------
    weeks = [
        ("winter", 2019, 1, 7),     # Mon Jan 7 2019
        ("summer", 2019, 7, 1),     # Mon Jul 1 2019
        ("dst_mar", 2019, 3, 25),   # week of last-Sunday March
        ("dst_oct", 2019, 10, 25),  # week of last-Sunday October
    ]
    for name, y, m, d in weeks:
        # every hour of the whole week + every 5 min on the DST Sundays
        for day_i in range(7):
            for hh in range(24):
                pts.append(_srv(y, m, d + day_i, hh))
        sun = {"dst_mar": 6, "dst_oct": 2}.get(name)   # the DST Sunday index
        if sun is not None:
            for mm in range(0, 24 * 60, 5):
                pts.append(_srv(y, m, d + sun, 0, mm))
    # ---- targeted regression points ---------------------------------------
    # server hours 00:00-03:59 across a winter and a summer day (neg-min bug)
    for y, m, d in [(2019, 1, 9), (2019, 7, 3)]:
        for mm in range(0, 4 * 60, 5):
            pts.append(_srv(y, m, d, 0, mm))
    # Friday boundary 19:00..22:00 both seasons
    for y, m, d in [(2019, 1, 11), (2019, 7, 5)]:
        for mm in range(19 * 60, 22 * 60, 5):
            pts.append(_srv(y, m, d, 0, mm))
    # session window edges (UTC minute grid -> server epochs)
    for y, m, d, off in [(2019, 1, 9, 2), (2019, 7, 3, 3)]:
        for umin in (299, 300, 301, 659, 660, 661, 689, 690, 691, 1049, 1050):
            utc_epoch = _srv(y, m, d) + umin * 60
            pts.append(int(pa_clock.utc_epoch_to_server(utc_epoch)))

    pts = sorted(set(pts))
    rows = []
    for t in pts:
        ct = t + 300                     # bar CLOSE epoch (M5 convention)
        rows.append((
            t,
            pa_clock.server_offset_hours(t),
            pa_clock.utc_minute_of_day(ct),
            (ct % DAY) // 60,
            pa_clock.server_dow(ct),
            veto(t),
            in_session(pa_clock.utc_minute_of_day(ct)),
        ))
    return rows


def main():
    rows = gen()
    inc = os.path.join(HERE, "clock_vectors.inc")
    with open(inc, "w") as f:
        f.write("// clock_vectors.inc - GENERATED by clock_vectors.py; "
                "do not edit\n")
        f.write("// row: t, off_h, utc_min(close), srv_min(close), "
                "dow(close), veto, in_session\n")
        f.write("#define PA_NV %d\n" % len(rows))
        f.write("const long   PA_V_T[PA_NV] = {")
        f.write(",".join(str(r[0]) for r in rows))
        f.write("};\n")
        for i, name in enumerate(
                ("PA_V_OFF", "PA_V_UMIN", "PA_V_SMIN", "PA_V_DOW",
                 "PA_V_VETO", "PA_V_SESS")):
            f.write("const int %s[PA_NV] = {" % name)
            f.write(",".join(str(r[i + 1]) for r in rows))
            f.write("};\n")
    csv = os.path.join(HERE, "clock_vectors.csv")
    with open(csv, "w") as f:
        f.write("t,off_h,utc_min,srv_min,dow,veto,in_session\n")
        for r in rows:
            f.write(",".join(str(x) for x in r) + "\n")
    print("wrote %d vectors -> %s , %s" % (len(rows), inc, csv))


if __name__ == "__main__":
    main()
