//+------------------------------------------------------------------+
//|                                                     PA_Clock.mqh |
//|  PA-PRO EA lane - server clock <-> UTC, EU DST (+2/+3).          |
//|                                                                  |
//|  Exact port of PA_Pro/lib/pa_clock.py (frozen semantics):        |
//|   - offset 3 while the SERVER wall clock lies inside             |
//|     [last Sunday of March 01:00, last Sunday of October 01:00),  |
//|     else 2   (eu_server_offset_hours, vpa_random_baseline.py:60) |
//|   - UTC minute-of-day wrapped mod 1440 (vpa_data.py:55-61 fix)   |
//|   - server_dow Monday=0: ((t//86400)+3)%7  (pandas weekday)      |
//|   - legacy_server_dow ((t//86400)+4)%7 Sunday=0 kept for parity  |
//|     notes only - "dow==4" under it fired on THURSDAY (R00 bug).  |
//|                                                                  |
//|  Golden vectors tested by mql5/tests/PA_Test_Session.mq5 and     |
//|  generated by mql5/tests/clock_vectors.py from pa_clock itself.  |
//|  No order, position or trade call exists in this header.         |
//+------------------------------------------------------------------+
#ifndef PA_CLOCK_MQH
#define PA_CLOCK_MQH

//--- pa_clock.server_offset_hours (scalar form)
//--- offset 3 when the server timestamp lies in
//--- [last Sunday of March + 1h, last Sunday of October + 1h) of its own year
int PaLastSundayOfMonth(const int year,const int month)
  {
   MqlDateTime dt;
   TimeToStruct(StringToTime(StringFormat("%04d.%02d.31",year,month)),dt);
   return(31-dt.day_of_week);
  }

int PaServerOffsetHours(const datetime server_time)
  {
   MqlDateTime dt;
   TimeToStruct(server_time,dt);
   datetime mar=(datetime)StringToTime(StringFormat("%04d.03.%02d 01:00",dt.year,
                                                   PaLastSundayOfMonth(dt.year,3)));
   datetime oct=(datetime)StringToTime(StringFormat("%04d.10.%02d 01:00",dt.year,
                                                   PaLastSundayOfMonth(dt.year,10)));
   return((server_time>=mar && server_time<oct) ? 3 : 2);
  }

//--- pa_clock.server_to_utc_epoch: UTC epoch = server epoch - offset(server)
long PaServerToUtc(const long server_epoch)
  {
   return(server_epoch-(long)PaServerOffsetHours((datetime)server_epoch)*3600);
  }

//--- pa_clock.utc_epoch_to_server: fixed-point scan over offsets {2,3};
//--- keep candidates whose own offset reproduces them, take the smallest;
//--- fallback: offset taken at the UTC instant itself (never observed here).
long PaUtcToServer(const long utc_epoch)
  {
   long best=0;
   bool found=false;
   for(int o=2;o<=3;o++)
     {
      long s=utc_epoch+(long)o*3600;
      if(PaServerOffsetHours((datetime)s)==o)
        {
         if(!found || s<best)
           {
            best=s;
            found=true;
           }
        }
     }
   if(found)
      return(best);
   return(utc_epoch+(long)PaServerOffsetHours((datetime)utc_epoch)*3600);
  }

//--- pa_clock.utc_minute_of_day: minute-of-day in [0,1440) of the UTC instant
//--- that corresponds to this SERVER timestamp (mod-1440 wrap; server 00:30
//--- in winter maps to 22:30 UTC of the previous day, never negative).
int PaUtcMinuteOfDay(const long server_epoch)
  {
   int off=PaServerOffsetHours((datetime)server_epoch);
   int srv_min=(int)((server_epoch%PA_DAY_SEC)/60);
   int m=(srv_min-off*60)%1440;
   if(m<0)
      m+=1440;
   return(m);
  }

int PaSrvMinuteOfDay(const long server_epoch)
  {
   return((int)((server_epoch%PA_DAY_SEC)/60));
  }

//--- pa_clock.server_dow: correct weekday of the server day, Monday=0..Sun=6
int PaServerDow(const long server_epoch)
  {
   return((int)(((server_epoch/PA_DAY_SEC)+3)%7));
  }

//--- pa_clock.legacy_server_dow: the frozen Sunday=0 convention under which
//--- "dow==4" fired on THURSDAY (the R00 Thursday-flatten bug).  Never used
//--- for trading decisions; kept for regression comparisons only.
int PaLegacyServerDow(const long server_epoch)
  {
   return((int)(((server_epoch/PA_DAY_SEC)+4)%7));
  }

//--- pa_clock.server_day_start_utc: UTC epoch of 00:00 server of the day
long PaServerDayStartUtc(const long server_epoch)
  {
   long day_start=(server_epoch/PA_DAY_SEC)*PA_DAY_SEC;
   return(PaServerToUtc(day_start));
  }

//--- fill a PaBar's close-derived clock fields (pa_data.resample :150-155:
//--- utc_min / srv_min / dow are all computed on the bar CLOSE = t + 300)
void PaBarClock(PaBar &b,const int bar_seconds)
  {
   long ct=b.t+(long)bar_seconds;
   b.srv_min=PaSrvMinuteOfDay(ct);
   b.utc_min=PaUtcMinuteOfDay(ct);
   b.dow=PaServerDow(ct);
  }

#endif // PA_CLOCK_MQH
