//+------------------------------------------------------------------+
//|                                                  PA_SelfTest.mqh |
//|  PA-PRO EA lane - golden-vector self test for PA_Clock +         |
//|  PA_Session.  Runs only when InpSelfTest=true (OnInit prints     |
//|  PASS/FAIL tallies and returns INIT_FAILED so the EA never       |
//|  trades in test mode).                                           |
//|                                                                  |
//|  Vectors come from tests/clock_vectors.inc, generated by         |
//|  tests/clock_vectors.py straight out of lib/pa_clock.py + the    |
//|  pa_fill.py entry-veto rules.  Weeks covered: winter, summer,    |
//|  both DST-change weeks, plus the negative-utc_min regression and |
//|  the Friday 20:00 boundary.                                      |
//+------------------------------------------------------------------+
#ifndef PA_SELFTEST_MQH
#define PA_SELFTEST_MQH

#include "PA_Types.mqh"
#include "PA_Clock.mqh"
#include "PA_Session.mqh"
#include "PA_Zones.mqh"
#include "tests\clock_vectors.inc"

//--- returns the number of failed assertions (prints each failure)
int PaRunClockSelfTest(CPaSession &sess)
  {
   int fail=0;
   for(int i=0;i<PA_NV;i++)
     {
      long t=PA_V_T[i];
      int off=PaServerOffsetHours((datetime)t);
      if(off!=PA_V_OFF[i])
        {
         PrintFormat("SELFTEST off t=%d got=%d want=%d",t,off,PA_V_OFF[i]);
         fail++;
        }
      int um=PaUtcMinuteOfDay(t+300);
      if(um!=PA_V_UMIN[i])
        {
         PrintFormat("SELFTEST utc_min t=%d got=%d want=%d",t,um,PA_V_UMIN[i]);
         fail++;
        }
      int sm=PaSrvMinuteOfDay(t+300);
      if(sm!=PA_V_SMIN[i])
        {
         PrintFormat("SELFTEST srv_min t=%d got=%d want=%d",t,sm,PA_V_SMIN[i]);
         fail++;
        }
      int dw=PaServerDow(t+300);
      if(dw!=PA_V_DOW[i])
        {
         PrintFormat("SELFTEST dow t=%d got=%d want=%d",t,dw,PA_V_DOW[i]);
         fail++;
        }
      int vt=sess.EntryVeto(t);
      if(vt!=PA_V_VETO[i])
        {
         PrintFormat("SELFTEST veto t=%d got=%d want=%d",t,vt,PA_V_VETO[i]);
         fail++;
        }
      bool ss=sess.InSessionUtcMin(um);
      if(ss!=(PA_V_SESS[i]!=0))
        {
         PrintFormat("SELFTEST sess t=%d got=%d want=%d",t,(int)ss,PA_V_SESS[i]);
         fail++;
        }
     }
   return(fail);
  }

//+------------------------------------------------------------------+
//| Incremental-vs-batch context proof: Init ctx1 on the first k0    |
//| bars then PushBar the rest one by one; Init ctx2 on the full n.  |
//| Both must agree bit-for-bit on every derived array (H1 buckets,  |
//| ATRs, h1_idx, pivot tables) — the live-bar path must be equal to |
//| the history path.  Returns the number of mismatched cells.       |
//+------------------------------------------------------------------+
int PaRunCtxSelfTest(const PaBar &bars[],const int n,const int k0)
  {
   int fail=0;
   CPaCtx c1,c2;
   if(!c1.Init(bars,k0,0.0001,"TEST") || !c2.Init(bars,n,0.0001,"TEST"))
      return(-1);
   for(int i=k0;i<n;i++)
      c1.PushBar(bars[i]);
   //--- H1 buckets
   if(c1.n_h1!=c2.n_h1)
     { PrintFormat("CTXTEST n_h1 %d != %d",c1.n_h1,c2.n_h1); fail++; }
   int m=MathMin(c1.n_h1,c2.n_h1);
   for(int i=0;i<m;i++)
      if(c1.h1_t[i]!=c2.h1_t[i] || c1.h1_o[i]!=c2.h1_o[i] ||
         c1.h1_h[i]!=c2.h1_h[i] || c1.h1_l[i]!=c2.h1_l[i] ||
         c1.h1_c[i]!=c2.h1_c[i])
        { PrintFormat("CTXTEST h1[%d] mismatch",i); fail++; }
   //--- ATRs + alignment (exact double equality - identical arithmetic)
   for(int i=0;i<n;i++)
     {
      if(c1.atr_m5_ok[i]!=c2.atr_m5_ok[i] ||
         (c1.atr_m5_ok[i] && c1.atr_m5[i]!=c2.atr_m5[i]) ||
         c1.h1_idx[i]!=c2.h1_idx[i])
        { PrintFormat("CTXTEST atr_m5/h1_idx[%d] mismatch",i); fail++; }
     }
   for(int i=0;i<m;i++)
      if(c1.atr_h1_ok[i]!=c2.atr_h1_ok[i] ||
         (c1.atr_h1_ok[i] && c1.atr_h1[i]!=c2.atr_h1[i]))
        { PrintFormat("CTXTEST atr_h1[%d] mismatch",i); fail++; }
   //--- pivot tables (force the lazy builds, then compare row-by-row)
   int p1=c1.Pivots3(), p2=c2.Pivots3();
   if(p1!=p2)
     { PrintFormat("CTXTEST piv3 count %d != %d",p1,p2); fail++; }
   for(int i=0;i<MathMin(p1,p2);i++)
      if(c1.piv3[i].idx!=c2.piv3[i].idx || c1.piv3[i].price!=c2.piv3[i].price ||
         c1.piv3[i].side!=c2.piv3[i].side || c1.piv3[i].confirm!=c2.piv3[i].confirm)
        { PrintFormat("CTXTEST piv3[%d] mismatch",i); fail++; }
   int q1=c1.H1Pivots2(), q2=c2.H1Pivots2();
   if(q1!=q2)
     { PrintFormat("CTXTEST h1p2 count %d != %d",q1,q2); fail++; }
   for(int i=0;i<MathMin(q1,q2);i++)
      if(c1.h1p2[i].h1_idx!=c2.h1p2[i].h1_idx ||
         c1.h1p2[i].price!=c2.h1p2[i].price ||
         c1.h1p2[i].m5_confirm!=c2.h1p2[i].m5_confirm ||
         c1.h1p2[i].m5_anchor!=c2.h1p2[i].m5_anchor)
        { PrintFormat("CTXTEST h1p2[%d] mismatch",i); fail++; }
   //--- H4 track (SF02 salience): buckets + raw +-2 pivot rows
   if(c1.n_h4!=c2.n_h4)
     { PrintFormat("CTXTEST n_h4 %d != %d",c1.n_h4,c2.n_h4); fail++; }
   int m4=MathMin(c1.n_h4,c2.n_h4);
   for(int i=0;i<m4;i++)
      if(c1.h4_t[i]!=c2.h4_t[i] || c1.h4_o[i]!=c2.h4_o[i] ||
         c1.h4_h[i]!=c2.h4_h[i] || c1.h4_l[i]!=c2.h4_l[i] ||
         c1.h4_c[i]!=c2.h4_c[i])
        { PrintFormat("CTXTEST h4[%d] mismatch",i); fail++; }
   int w1=c1.H4Pivots2(), w2=c2.H4Pivots2();
   if(w1!=w2)
     { PrintFormat("CTXTEST h4raw2 count %d != %d",w1,w2); fail++; }
   for(int i=0;i<MathMin(w1,w2);i++)
      if(c1.h4raw2[i].idx!=c2.h4raw2[i].idx ||
         c1.h4raw2[i].price!=c2.h4raw2[i].price ||
         c1.h4raw2[i].side!=c2.h4raw2[i].side ||
         c1.h4raw2[i].confirm!=c2.h4raw2[i].confirm)
        { PrintFormat("CTXTEST h4raw2[%d] mismatch",i); fail++; }
   return(fail);
  }

//+------------------------------------------------------------------+
//| Zone-level incremental proof: engine A inits on the first k0     |
//| bars then PushBar+StepBar one bar at a time to n; engine B inits |
//| on all n and steps the same prefix->live schedule.  Armed views  |
//| must be identical on every pushed bar, for every generator — the |
//| live path (PushBar + lazy pivot/sync streams) must equal the     |
//| batch path bit-for-bit.  Returns the number of mismatched cells. |
//+------------------------------------------------------------------+
int PaRunZoneSelfTest(const PaBar &bars[],const int n,const int k0)
  {
   bool gen_on[PA_GEN_COUNT];
   for(int g=0;g<PA_GEN_COUNT;g++)
      gen_on[g]=true;
   CPaPerception pa1,pa2;
   if(!pa1.Init(bars,k0,0.0001,"TEST",gen_on) ||
      !pa2.Init(bars,n,0.0001,"TEST",gen_on))
      return(-1);
   pa1.RunTo(k0-1);
   pa2.RunTo(k0-1);
   int fail=0;
   PaZoneView v1[],v2[];
   for(int i=k0;i<n;i++)
     {
      pa1.ctx.PushBar(bars[i]);
      pa1.StepBar(i);
      pa2.StepBar(i);               // refs sit at bar i for both engines
      for(int g=0;g<PA_GEN_COUNT;g++)
        {
         int c1=pa1.ViewsAt(g,i,true,v1);
         int c2=pa2.ViewsAt(g,i,true,v2);
         if(c1!=c2)
           {
            PrintFormat("ZONETEST t=%d gen=%d armed %d != %d",i,g,c1,c2);
            fail++;
            continue;
           }
         for(int k=0;k<c1;k++)
            if(v1[k].lo!=v2[k].lo || v1[k].hi!=v2[k].hi ||
               v1[k].strength!=v2[k].strength ||
               v1[k].touches!=v2[k].touches ||
               v1[k].n_respected!=v2[k].n_respected ||
               v1[k].broken_idx!=v2[k].broken_idx ||
               v1[k].role_flip!=v2[k].role_flip ||
               v1[k].approach_side!=v2[k].approach_side ||
               v1[k].born_idx!=v2[k].born_idx ||
               v1[k].quality!=v2[k].quality)
              {
               PrintFormat("ZONETEST t=%d gen=%d row=%d zid=%d/%d mismatch",
                           i,g,k,v1[k].zid,v2[k].zid);
               fail++;
              }
        }
     }
   //--- pass 2: SF02 salience mode 1 + top-k=2 arming.  Exercises the H4
   //--- bucket/pivot track (ctx.PivotNear) and the salience-ranked arm
   //--- order incremental-vs-batch; a divergence in h4raw2 shows up as a
   //--- salience or armed-set mismatch here.
   CPaPerception pa3,pa4;
   if(!pa3.Init(bars,k0,0.0001,"TEST",gen_on) ||
      !pa4.Init(bars,n,0.0001,"TEST",gen_on))
      return(fail>0?fail:-2);
   for(int g=0;g<PA_GEN_COUNT;g++)
     {
      if(pa3.gen[g]!=NULL)
        { pa3.gen[g].cfg_salience_mode=1; pa3.gen[g].cfg_arm_topk=2; }
      if(pa4.gen[g]!=NULL)
        { pa4.gen[g].cfg_salience_mode=1; pa4.gen[g].cfg_arm_topk=2; }
     }
   pa3.RunTo(k0-1);
   pa4.RunTo(k0-1);
   for(int i=k0;i<n;i++)
     {
      pa3.ctx.PushBar(bars[i]);
      pa3.StepBar(i);
      pa4.StepBar(i);
      for(int g=0;g<PA_GEN_COUNT;g++)
        {
         int c1=pa3.ViewsAt(g,i,true,v1);
         int c2=pa4.ViewsAt(g,i,true,v2);
         if(c1!=c2)
           {
            PrintFormat("ZONETEST-SF2 t=%d gen=%d armed %d != %d",i,g,c1,c2);
            fail++;
            continue;
           }
         for(int k=0;k<c1;k++)
            if(v1[k].zid!=v2[k].zid || v1[k].salience!=v2[k].salience ||
               v1[k].lo!=v2[k].lo || v1[k].hi!=v2[k].hi)
              {
               PrintFormat("ZONETEST-SF2 t=%d gen=%d row=%d zid=%d/%d mismatch",
                           i,g,k,v1[k].zid,v2[k].zid);
               fail++;
              }
        }
     }
   return(fail);
  }

#endif // PA_SELFTEST_MQH
