<#
.SYNOPSIS
    Detect MT5 install/data paths on this machine and write alpha.local.ps1.
.EXAMPLE
    .\tools\init_machine_paths.ps1
    .\tools\init_machine_paths.ps1 -Force
#>
param(
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$AlphaRoot = Split-Path -Parent $PSScriptRoot
$OutPath = Join-Path $AlphaRoot "alpha.local.ps1"
$ExamplePath = Join-Path $AlphaRoot "alpha.local.ps1.example"

function Resolve-Mt5InstallRoot {
    $candidates = @(
        "C:\Program Files\MetaTrader 5",
        "C:\Program Files (x86)\MetaTrader 5"
    )
    foreach ($root in $candidates) {
        if (Test-Path -LiteralPath (Join-Path $root "terminal64.exe") -PathType Leaf) {
            return $root
        }
    }
    return $null
}

function Resolve-Mt5DataRoot([string]$InstallRoot) {
    $termRoot = Join-Path $env:APPDATA "MetaQuotes\Terminal"
    if (-not (Test-Path -LiteralPath $termRoot -PathType Container)) {
        return $null
    }
    $dirs = @(Get-ChildItem -LiteralPath $termRoot -Directory -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -match '^[A-F0-9]{32}$' -and (Test-Path -LiteralPath (Join-Path $_.FullName "MQL5") -PathType Container) })
    if ($dirs.Count -eq 0) { return $null }

    Write-Host "Detected terminal data folders:" -ForegroundColor Cyan
    foreach ($d in $dirs) {
        $origin = Join-Path $d.FullName "origin.txt"
        $originVal = if (Test-Path -LiteralPath $origin -PathType Leaf) {
            (Get-Content -LiteralPath $origin -Raw).Trim()
        } else { "(no origin.txt)" }
        Write-Host "  $($d.Name)  origin=$originVal"
    }

    if (-not [string]::IsNullOrWhiteSpace($InstallRoot)) {
        $matched = @($dirs | Where-Object {
            $origin = Join-Path $_.FullName "origin.txt"
            if (-not (Test-Path -LiteralPath $origin -PathType Leaf)) { return $false }
            $originVal = (Get-Content -LiteralPath $origin -Raw).Trim()
            return ($originVal -ieq $InstallRoot)
        })
        if ($matched.Count -ge 1) { return $matched[0].FullName }
    }
    return $dirs[0].FullName
}

if ((Test-Path -LiteralPath $OutPath -PathType Leaf) -and -not $Force) {
    throw "Refusing to overwrite existing $OutPath (pass -Force to replace)."
}

$install = Resolve-Mt5InstallRoot
if (-not $install) {
    throw "Could not find MetaTrader 5 install (terminal64.exe). Install MT5 or edit $ExamplePath manually."
}

$data = Resolve-Mt5DataRoot $install
if (-not $data) {
    throw "Could not find MT5 terminal data under $env:APPDATA\MetaQuotes\Terminal. Open MT5 once, then retry."
}

$content = @"
# Auto-generated by tools/init_machine_paths.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# Machine-local only - do not commit this file.
`$MT5InstallRoot = "$install"
`$MT5DataRoot = "$data"
`$MT5PortableMode = `$false
`$MT5CommonFilesRoot = Join-Path (Split-Path -Parent `$MT5DataRoot) "Common\Files"
`$MT5AllowCommonFiles = `$true
`$MT5TesterRoot = Join-Path `$MT5DataRoot "Tester"
`$MT5RequiredStorageDrive = ""
"@

Set-Content -LiteralPath $OutPath -Value $content -Encoding UTF8
Write-Host ""
Write-Host "Wrote: $OutPath" -ForegroundColor Green
Write-Host "  Install: $install"
Write-Host "  Data:    $data"
Write-Host ""
Write-Host "Verify with: .\alpha.ps1 status" -ForegroundColor Cyan
