<#
.SYNOPSIS
    Detect a factory portable isolate and write alpha.local.ps1.
.EXAMPLE
    .\tools\init_machine_paths.ps1
    .\tools\init_machine_paths.ps1 -Force
#>
param(
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$AlphaRoot = Split-Path -Parent $PSScriptRoot
$OutPath = Join-Path $AlphaRoot "alpha.local.ps1"
$ExamplePath = Join-Path $AlphaRoot "alpha.local.ps1.example"

function Resolve-FactoryPortableRoot {
    $candidates = @(
        (Join-Path $AlphaRoot "runtime\mt5-portable-mqdemo"),
        (Join-Path $AlphaRoot "runtime\mt5-portable-fivepercent")
    )
    foreach ($root in $candidates) {
        $exe = Join-Path $root "terminal64.exe"
        $mql5 = Join-Path $root "MQL5"
        if ((Test-Path -LiteralPath $exe -PathType Leaf) -and (Test-Path -LiteralPath $mql5 -PathType Container)) {
            return (Get-Item -LiteralPath $root).FullName
        }
    }
    return $null
}

if ((Test-Path -LiteralPath $OutPath -PathType Leaf) -and -not $Force) {
    throw "Refusing to overwrite existing $OutPath (pass -Force to replace)."
}

$portable = Resolve-FactoryPortableRoot
if (-not $portable) {
    throw "No AlphaFactory portable isolate found under runtime\mt5-portable-mqdemo or runtime\mt5-portable-fivepercent. Refusing to pin Owner Program Files / AppData. Copy a portable terminal into runtime, or edit $ExamplePath."
}

$drive = [System.IO.Path]::GetPathRoot($portable).TrimEnd([char[]]'\/').ToUpperInvariant()
$common = Join-Path $portable "Common\Files"
if (-not (Test-Path -LiteralPath $common -PathType Container)) {
    New-Item -ItemType Directory -Path $common -Force | Out-Null
}

$content = @"
# Auto-generated by tools/init_machine_paths.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# Machine-local only - do not commit this file.
# Owner GUI (Program Files, AppData clones, and the root you trade from) is not
# a factory target. Path is written relative to this file so moving the repo
# does not silently retarget the factory.
`$MT5InstallRoot = Join-Path `$PSScriptRoot "runtime\mt5-portable-mqdemo"
`$MT5DataRoot = `$MT5InstallRoot
`$MT5PortableMode = `$true
`$MT5CommonFilesRoot = Join-Path `$MT5DataRoot "Common\Files"
`$MT5AllowCommonFiles = `$true
`$MT5TesterRoot = Join-Path `$MT5DataRoot "Tester"
`$MT5RequiredStorageDrive = "$drive"
"@

Set-Content -LiteralPath $OutPath -Value $content -Encoding UTF8
Write-Host ""
Write-Host "Wrote: $OutPath" -ForegroundColor Green
Write-Host "  Install: $portable"
Write-Host "  Data:    $portable"
Write-Host "  Common:  $common"
Write-Host "  Drive:   $drive"
Write-Host ""
Write-Host "Verify with: .\alpha.ps1 status" -ForegroundColor Cyan
Write-Host "Launch this tree only with /portable. Do not double-click terminal64.exe." -ForegroundColor Yellow
