"""Generate the immutable HYP013 MQL5 event-flow table.

This transform is outcome-blind: it reads only the HYP012 aggregate flow CSV
and the already-verified FivePercent server clock model.
"""

from __future__ import annotations

import csv
import hashlib
import importlib.util
from datetime import datetime, timedelta, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
SOURCE = (
    ROOT
    / "03. EA Developer/EA_EventAggressorFlow/research/evidence"
    / "HYP-EVENT-AGGFLOW-EURUSD-TICK-012"
    / "EVENTAGGFLOW012-SOURCE-QUALITY-001/event_signed_flow.csv"
)
OUTPUT = ROOT / "03. EA Developer/EA_EventAggressorFlow/resources/event_aggflow_013_table.mqh"
CLOCK_MODULE = ROOT / "02. AlphaFactory/tools/research/fivepercent_server_clock.py"
EXPECTED_SOURCE_SHA256 = "65AA6558629F6FF224E5DB6FD218B1DC9A4EC6A7B07DE886C3FE13E5922A106C"


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def load_clock_module():
    spec = importlib.util.spec_from_file_location("fivepercent_server_clock", CLOCK_MODULE)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load canonical FivePercent clock module")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def parse_utc(value: str) -> datetime:
    parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        raise ValueError(f"event timestamp lacks UTC offset: {value}")
    return parsed.astimezone(timezone.utc)


def utc_to_server(utc: datetime, clock) -> tuple[datetime, int]:
    # The canonical helper exposes server->UTC. For 2019-2020, determine the
    # unique +2/+3 inverse and require an exact round trip.
    candidates: list[tuple[datetime, int]] = []
    for offset in (2, 3):
        server = (utc + timedelta(hours=offset)).replace(tzinfo=None)
        if clock.server_to_utc(server).replace(tzinfo=timezone.utc) == utc:
            candidates.append((server, offset))
    if len(candidates) != 1:
        raise ValueError(f"ambiguous FivePercent UTC->server mapping: {utc.isoformat()}")
    return candidates[0]


def to_epoch_msc_naive(value: datetime) -> int:
    return int(value.replace(tzinfo=timezone.utc).timestamp() * 1000)


def load_rows() -> list[dict[str, int | str]]:
    actual_hash = sha256_file(SOURCE)
    if actual_hash != EXPECTED_SOURCE_SHA256:
        raise ValueError(f"source SHA256 mismatch: {actual_hash}")
    clock = load_clock_module()
    rows: list[dict[str, int | str]] = []
    with SOURCE.open("r", encoding="utf-8", newline="") as handle:
        for raw in csv.DictReader(handle):
            event_id = str(raw["request_id"])
            utc = parse_utc(str(raw["event_time_utc"]))
            server, offset = utc_to_server(utc, clock)
            rows.append(
                {
                    "event_id": event_id,
                    "utc_msc": int(utc.timestamp() * 1000),
                    "server_msc": to_epoch_msc_naive(server),
                    "offset_h": offset,
                    "flow": int(raw["signed_flow"]),
                }
            )
    if len(rows) != 329 or len({row["event_id"] for row in rows}) != 329:
        raise ValueError("expected exactly 329 unique DESIGN identities")
    if [row["event_id"] for row in rows] != [f"EVT{i:04d}" for i in range(1, 330)]:
        raise ValueError("event identity sequence mismatch")
    if any(int(rows[i]["server_msc"]) >= int(rows[i + 1]["server_msc"]) for i in range(328)):
        raise ValueError("server clocks are not strictly increasing")
    flows = [int(row["flow"]) for row in rows]
    if (sum(flow > 0 for flow in flows), sum(flow < 0 for flow in flows), sum(flow == 0 for flow in flows)) != (156, 170, 3):
        raise ValueError("frozen BUY/SELL/zero counts changed")
    return rows


def canonical_table(rows: list[dict[str, int | str]]) -> bytes:
    return "".join(
        f"{row['event_id']},{row['utc_msc']},{row['server_msc']},{row['flow']}\n"
        for row in rows
    ).encode("utf-8")


def mql_array(name: str, kind: str, values: list[str]) -> str:
    body = ",\n   ".join(values)
    return f"const {kind} {name}[AF_FLOW_EVENT_COUNT]={{\n   {body}\n}};\n"


def render(rows: list[dict[str, int | str]]) -> str:
    table_sha = hashlib.sha256(canonical_table(rows)).hexdigest().upper()
    parts = [
        "// Generated by research/generate_event_table.py; do not hand-edit.\n",
        "#ifndef EVENT_AGGFLOW_013_TABLE_MQH\n#define EVENT_AGGFLOW_013_TABLE_MQH\n\n",
        "#define AF_FLOW_EVENT_COUNT 329\n",
        f'const string AF_FLOW_SOURCE_SHA256="{EXPECTED_SOURCE_SHA256}";\n',
        f'const string AF_FLOW_TABLE_SHA256="{table_sha}";\n\n',
        mql_array("AF_FLOW_EVENT_ID", "string", [f'"{row["event_id"]}"' for row in rows]),
        "\n",
        mql_array("AF_FLOW_UTC_MSC", "long", [str(row["utc_msc"]) for row in rows]),
        "\n",
        mql_array("AF_FLOW_SERVER_MSC", "long", [str(row["server_msc"]) for row in rows]),
        "\n",
        mql_array("AF_FLOW_SIGNED", "long", [str(row["flow"]) for row in rows]),
        "\n#endif\n",
    ]
    return "".join(parts)


def main() -> None:
    rows = load_rows()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(rows), encoding="utf-8", newline="\n")
    print(
        "EVENTAGGFLOW013_TABLE_OK "
        f"events={len(rows)} source_sha256={EXPECTED_SOURCE_SHA256} "
        f"table_sha256={hashlib.sha256(canonical_table(rows)).hexdigest().upper()}"
    )


if __name__ == "__main__":
    main()

